### ISSUE TITLE
`accounts: Vec<_>`

### ISSUE THREAD

**Issue by cavemanloverboy** [buffalojoec/mollusk#2]
Why is this a vector?

https://github.com/buffalojoec/mollusk/blob/e861087f3d4f61fcbb942fb056d701f068c60822/harness/src/lib.rs#L158-L162

Should make this a slice so that devs don't have to clone (and so you don't have to clone internally on each loop iteration).

**Comment by cavemanloverboy** [comment]
I can submit PR if you agree, just say the word

**Comment by buffalojoec** [comment]
Yep, definitely agree! I made this a slice originally, but since `TransactionContext` takes a vector, I didn't manage to see a good way around cloning within the harness, so I left it up to the developer to decide if they wanted to clone when providing the accounts.

If you can make it work without cloning, I'm game!

**Comment by cavemanloverboy** [comment]
Even if you end up doing copies internally, It's one less copy (devs have to clone the vector due to your interface and then it's internally copied onto the `transaction_accounts` buffer again). And, I think it's a nicer API.

**Comment by buffalojoec** [comment]
> Even if you end up doing copies internally, It's one less copy (devs have to clone the vector due to your interface and then it's internally copied onto the `transaction_accounts` buffer again). And, I think it's a nicer API.

Works for me! Thanks!

**Comment by cavemanloverboy** [comment]
https://github.com/buffalojoec/mollusk/pull/6
